[GENERAL]
SIMILARITY_MEASURE = "cosine"

[MODELS.OLLAMA]
API_URL = "http://ollama:11434"

[API_ENDPOINTS]
SEARXNG = "http://searxng:8080"

[MODELS.OPENAI]
API_KEY = ""

[MODELS.GROQ]
API_KEY = ""

[MODELS.ANTHROPIC]
API_KEY = ""

[MODELS.GEMINI]
API_KEY = ""

[MODELS.CUSTOM_OPENAI]
API_KEY = ""
API_URL = ""
MODEL_NAME = ""

[MODELS.DEEPSEEK]
API_KEY = ""

[MODELS.LM_STUDIO]
API_URL = ""
