services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 11434:11434
    environment:
      - OLLAMA_FLASH_ATTENTION=1
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - internal

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBUI_AUTH=false
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./open-webui:/app/backend/data
    networks:
      - internal

  comfyui:
    image: yanwk/comfyui-boot:cu124-slim
    container_name: comfyui
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8188:8188
    environment:
      - CLI_ARGS=--lowvram
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ./storage:/root
      - ./storage-models/models:/root/ComfyUI/models
      - ./storage-models/hf-hub:/root/.cache/huggingface/hub
      - ./storage-models/torch-hub:/root/.cache/torch/hub
      - ./storage-user/input:/root/ComfyUI/input
      - ./storage-user/output:/root/ComfyUI/output
      - ./storage-user/workflows:/root/ComfyUI/user/default/workflows
    networks:
      - internal

networks:
  internal: null
