server {
    listen 80;

    server_name comfyui.local;

    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.4:8188;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
