server {
    listen 80;

    server_name vane.local;

    client_max_body_size 0;
    
    location / {
        proxy_pass http://127.0.0.8:3000/;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
